/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BackgroundProcesser: typeof import('./src/components/BackgroundProcesser/index.vue')['default']
    ColorPicker: typeof import('./src/components/ColorPicker/index.vue')['default']
    ComponentList: typeof import('./src/components/ComponentList/index.vue')['default']
    ContextMenu: typeof import('./src/components/ContextMenu/index.vue')['default']
    Dragg: typeof import('./src/components/LayerList/dragg.vue')['default']
    EditGroup: typeof import('./src/components/EditGroup/index.vue')['default']
    EditWrapper: typeof import('./src/components/EditWrapper/index.vue')['default']
    HeaderBar: typeof import('./src/components/HeaderBar/index.vue')['default']
    ImageProcesser: typeof import('./src/components/ImageProcesser/index.vue')['default']
    InlineEditor: typeof import('./src/components/InlineEditor/index.vue')['default']
    LayerList: typeof import('./src/components/LayerList/index.vue')['default']
    PText: typeof import('./src/components/PText/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectTable: typeof import('./src/components/SelectTable/index.vue')['default']
    ShadowPicker: typeof import('./src/components/ShadowPicker/index.vue')['default']
    TemplateList: typeof import('./src/components/TemplateList/index.vue')['default']
    Upload: typeof import('./src/components/Upload/index.vue')['default']
    UserProfile: typeof import('./src/components/UserProfile.vue')['default']
  }
}
